version: '3.2'

services:
  eureka:
    image: steeltoeoss/eurekaserver
    ports:
      - 8761:8761
  gateway:
    build: ./gateway
    depends_on:
      - eureka
    ports:
      - 8080:80
    command: ["./wait-for-it.sh","eureka:8761","--timeout=-1","--","dotnet", "gateway.dll"]
    environment:
      "Logging:LogLevel:Default": "Trace"
  users:
    build: ./users
    depends_on:
      - eureka
    ports:
      - 8081:80
    command: ["./wait-for-it.sh","eureka:8761","--timeout=-1","--","dotnet", "users.dll"]
    environment:
      "Logging:LogLevel:Default": "Trace"
  inventory:
    build: ./inventory
    depends_on:
      - eureka
    ports:
      - 8082:80
    command: ["./wait-for-it.sh","eureka:8761","--timeout=-1","--","dotnet", "inventory.dll"]
    environment:
      "Logging:LogLevel:Default": "Trace"