version: '3.2'

services:
  eureka:
    image: steeltoeoss/eurekaserver
    ports:
      - 8761:8761
  users:
    build: ./users
    depends_on:
      - eureka
    ports:
      - 8080:80
    command: ["./wait-for-it.sh","eureka:8761","--timeout=-1","--","dotnet", "users.dll"]
    environment:
      "Logging:LogLevel:Default": "Debug"